# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
name: Build EXE for TestDriver
env:
  DEBUG: napi:*

on:
  pull_request:

jobs:
  build:
    name: build windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - name: Install pnpm explicitly
        run: |
          npm install -g pnpm
          pnpm --version  # Verify pnpm is installed and available

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          architecture: x64

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Install dependencies (root)
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Install dependencies (examples/api)
        working-directory: examples/api
        run: pnpm i

      - name: Build CLI
        run: pnpm run build:cli
        shell: bash

      - name: Build API
        run: pnpm run build:api
        shell: bash

      - name: Set environment variables
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "GITHUB_RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV

      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: | 
            # 1. /run testdriver/tauri_api_install.yml
            # 2. /run testdriver/dark_light_mode.yml
            # 3. /run testdriver/minimize_maximize.yml
            1. /run testdriver/comm_echo.yml
            2. /run testdriver/comm_send_event_rust.yml
            3. /run testdriver/comm_spam.yml
            4. /run testdriver/comm_call_request_api.yml
            # 7. /run testdriver/comm_call_log_api.yml
            
          prerun: |
            $headers = @{
                Authorization = "token ${{ secrets.GITHUB_TOKEN }}"
            }

            # Ensure we are in the correct base directory before switching
            $baseDirectory = "${{ github.workspace }}"  # GitHub Actions workspace root
            Set-Location -Path $baseDirectory
              
            # Build API Dev App
            Write-Host "Building API Dev App..."
            Set-Location -Path "examples/api"
            pnpm tauri dev
            Write-Host "API Dev App built successfully."
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
